### ISSUE TITLE
[Meta] ESS/Serverless Observability features benchmarking

### ISSUE THREAD

**Issue by ablnk** [elastic/oblt-playwright#1]
```[tasklist]
### Tasks
- [x] Support the framework to run tests in serverless.
- [x] Decide on use of Synthetics in addition to measuring api response
- [ ] https://github.com/elastic/oblt-playwright/issues/3
- [ ] https://github.com/elastic/oblt-playwright/issues/2
- [ ] https://github.com/elastic/observability-perf/issues/687
- [ ] https://github.com/elastic/observability-perf/issues/689
- [ ] https://github.com/elastic/observability-perf/issues/691
- [ ] Support nginx package data generation.
- [ ] Support k8s package data generation.
```

**Comment by ruflin** [comment]
Related to this issue, here are benchmark templates in the work for nginx:

* https://github.com/elastic/integrations/pull/8762
* https://github.com/elastic/integrations/pull/8777
* https://github.com/elastic/integrations/pull/8781
